# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/channel/ip/channel_cordic_0_0/channel_cordic_0_0.xci
# IP: The module: 'channel_cordic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/channel/ip/channel_cordic_0_0/channel_cordic_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'channel_cordic_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/channel/ip/channel_cordic_0_0/channel_cordic_0_0.xci
# IP: The module: 'channel_cordic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/channel/ip/channel_cordic_0_0/channel_cordic_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'channel_cordic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
