# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/system/ip/system_fir_compiler_0_1/system_fir_compiler_0_1.xci
# IP: The module: 'system_fir_compiler_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/system/ip/system_fir_compiler_0_1/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_compiler_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/system/ip/system_fir_compiler_0_1/system_fir_compiler_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_compiler_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/system/ip/system_fir_compiler_0_1/system_fir_compiler_0_1.xci
# IP: The module: 'system_fir_compiler_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/system/ip/system_fir_compiler_0_1/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_compiler_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/system/ip/system_fir_compiler_0_1/system_fir_compiler_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_compiler_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
