#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Mar 16 22:23:00 IST 2024
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_behav -key {Behavioral:sim_1:Functional:tb} -tclbatch tb.tcl -protoinst "protoinst_files/design_4.protoinst" -protoinst "protoinst_files/sig_gen.protoinst" -protoinst "protoinst_files/system.protoinst" -protoinst "protoinst_files/design_2.protoinst" -protoinst "protoinst_files/design_1.protoinst" -protoinst "protoinst_files/channel.protoinst" -view /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/top_tb_behav.wcfg -log simulate.log"
xsim tb_behav -key {Behavioral:sim_1:Functional:tb} -tclbatch tb.tcl -protoinst "protoinst_files/design_4.protoinst" -protoinst "protoinst_files/sig_gen.protoinst" -protoinst "protoinst_files/system.protoinst" -protoinst "protoinst_files/design_2.protoinst" -protoinst "protoinst_files/design_1.protoinst" -protoinst "protoinst_files/channel.protoinst" -view /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/top_tb_behav.wcfg -log simulate.log

