# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/design_4/ip/design_4_blk_mem_gen_0_1/design_4_blk_mem_gen_0_1.xci
# IP: The module: 'design_4_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/design_4/ip/design_4_blk_mem_gen_0_1/design_4_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/design_4/ip/design_4_blk_mem_gen_0_1/design_4_blk_mem_gen_0_1.xci
# IP: The module: 'design_4_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/shahar/Downloads/anton/redpitaya_guide/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/design_4/ip/design_4_blk_mem_gen_0_1/design_4_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
