# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/shahar/Downloads/anton/redpitaya_guide/cfg/clocks.xdc

# XDC: /home/shahar/Downloads/anton/redpitaya_guide/cfg/ports.xdc

# Block Designs: bd/design_4/design_4.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4 || ORIG_REF_NAME==design_4} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_1_0/design_4_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_1_0 || ORIG_REF_NAME==design_4_xlslice_1_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_2_0/design_4_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_2_0 || ORIG_REF_NAME==design_4_xlslice_2_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlconstant_2_0/design_4_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlconstant_2_0 || ORIG_REF_NAME==design_4_xlconstant_2_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axis_red_pitaya_adc_0_0/design_4_axis_red_pitaya_adc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==design_4_axis_red_pitaya_adc_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlconcat_0_0/design_4_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlconcat_0_0 || ORIG_REF_NAME==design_4_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_blk_mem_gen_0_0/design_4_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_blk_mem_gen_0_0 || ORIG_REF_NAME==design_4_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axi_bram_reader_0_0/design_4_axi_bram_reader_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_axi_bram_reader_0_0 || ORIG_REF_NAME==design_4_axi_bram_reader_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_blk_mem_gen_1_0/design_4_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_blk_mem_gen_1_0 || ORIG_REF_NAME==design_4_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axi_bram_reader_1_0/design_4_axi_bram_reader_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_axi_bram_reader_1_0 || ORIG_REF_NAME==design_4_axi_bram_reader_1_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_util_ds_buf_1_0/design_4_util_ds_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_util_ds_buf_1_0 || ORIG_REF_NAME==design_4_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_util_ds_buf_2_0/design_4_util_ds_buf_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_util_ds_buf_2_0 || ORIG_REF_NAME==design_4_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axis_red_pitaya_dac_0_0/design_4_axis_red_pitaya_dac_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_axis_red_pitaya_dac_0_0 || ORIG_REF_NAME==design_4_axis_red_pitaya_dac_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlconstant_0_0/design_4_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlconstant_0_0 || ORIG_REF_NAME==design_4_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlconcat_1_0/design_4_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlconcat_1_0 || ORIG_REF_NAME==design_4_xlconcat_1_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_3_0/design_4_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_3_0 || ORIG_REF_NAME==design_4_xlslice_3_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlconstant_3_0/design_4_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlconstant_3_0 || ORIG_REF_NAME==design_4_xlconstant_3_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_4_0/design_4_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_4_0 || ORIG_REF_NAME==design_4_xlslice_4_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_dds_compiler_0_0/design_4_dds_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_dds_compiler_0_0 || ORIG_REF_NAME==design_4_dds_compiler_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_clk_wiz_0_0/design_4_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_clk_wiz_0_0 || ORIG_REF_NAME==design_4_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlconstant_1_0/design_4_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlconstant_1_0 || ORIG_REF_NAME==design_4_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_1_1/design_4_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_1_1 || ORIG_REF_NAME==design_4_xlslice_1_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_2_1/design_4_xlslice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_2_1 || ORIG_REF_NAME==design_4_xlslice_2_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_3_1/design_4_xlslice_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_3_1 || ORIG_REF_NAME==design_4_xlslice_3_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_4_1/design_4_xlslice_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_4_1 || ORIG_REF_NAME==design_4_xlslice_4_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axi_gpio_1_0/design_4_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_axi_gpio_1_0 || ORIG_REF_NAME==design_4_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlconstant_0_1/design_4_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlconstant_0_1 || ORIG_REF_NAME==design_4_xlconstant_0_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axi_gpio_1_1/design_4_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_axi_gpio_1_1 || ORIG_REF_NAME==design_4_axi_gpio_1_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlconcat_0_1/design_4_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlconcat_0_1 || ORIG_REF_NAME==design_4_xlconcat_0_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axi_gpio_0_0/design_4_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_axi_gpio_0_0 || ORIG_REF_NAME==design_4_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_blk_mem_gen_0_1/design_4_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_blk_mem_gen_0_1 || ORIG_REF_NAME==design_4_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_c_counter_binary_0_0/design_4_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_c_counter_binary_0_0 || ORIG_REF_NAME==design_4_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_cordic_0_0/design_4_cordic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_cordic_0_0 || ORIG_REF_NAME==design_4_cordic_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_dds_compiler_1_0/design_4_dds_compiler_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_dds_compiler_1_0 || ORIG_REF_NAME==design_4_dds_compiler_1_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_ff_0_0/design_4_ff_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_ff_0_0 || ORIG_REF_NAME==design_4_ff_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_ff_1_0/design_4_ff_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_ff_1_0 || ORIG_REF_NAME==design_4_ff_1_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_ff_2_0/design_4_ff_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_ff_2_0 || ORIG_REF_NAME==design_4_ff_2_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_fir_compiler_0_0/design_4_fir_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_fir_compiler_0_0 || ORIG_REF_NAME==design_4_fir_compiler_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_fir_compiler_1_0/design_4_fir_compiler_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_fir_compiler_1_0 || ORIG_REF_NAME==design_4_fir_compiler_1_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_mult_gen_0_0/design_4_mult_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_mult_gen_0_0 || ORIG_REF_NAME==design_4_mult_gen_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_mult_gen_1_0/design_4_mult_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_mult_gen_1_0 || ORIG_REF_NAME==design_4_mult_gen_1_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_signal_spliter_1_0/design_4_signal_spliter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_signal_spliter_1_0 || ORIG_REF_NAME==design_4_signal_spliter_1_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlconcat_4_0/design_4_xlconcat_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlconcat_4_0 || ORIG_REF_NAME==design_4_xlconcat_4_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_5_0/design_4_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_5_0 || ORIG_REF_NAME==design_4_xlslice_5_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_6_0/design_4_xlslice_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_6_0 || ORIG_REF_NAME==design_4_xlslice_6_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_7_0/design_4_xlslice_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_7_0 || ORIG_REF_NAME==design_4_xlslice_7_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_8_0/design_4_xlslice_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_8_0 || ORIG_REF_NAME==design_4_xlslice_8_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_9_0/design_4_xlslice_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_9_0 || ORIG_REF_NAME==design_4_xlslice_9_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_10_0/design_4_xlslice_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_10_0 || ORIG_REF_NAME==design_4_xlslice_10_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_cordic_0_1/design_4_cordic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_cordic_0_1 || ORIG_REF_NAME==design_4_cordic_0_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_dds_compiler_1_1/design_4_dds_compiler_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_dds_compiler_1_1 || ORIG_REF_NAME==design_4_dds_compiler_1_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_ff_0_1/design_4_ff_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_ff_0_1 || ORIG_REF_NAME==design_4_ff_0_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_ff_1_1/design_4_ff_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_ff_1_1 || ORIG_REF_NAME==design_4_ff_1_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_ff_2_1/design_4_ff_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_ff_2_1 || ORIG_REF_NAME==design_4_ff_2_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_fir_compiler_0_1/design_4_fir_compiler_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_fir_compiler_0_1 || ORIG_REF_NAME==design_4_fir_compiler_0_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_fir_compiler_1_1/design_4_fir_compiler_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_fir_compiler_1_1 || ORIG_REF_NAME==design_4_fir_compiler_1_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_mult_gen_0_1/design_4_mult_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_mult_gen_0_1 || ORIG_REF_NAME==design_4_mult_gen_0_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_mult_gen_1_1/design_4_mult_gen_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_mult_gen_1_1 || ORIG_REF_NAME==design_4_mult_gen_1_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_signal_spliter_1_1/design_4_signal_spliter_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_signal_spliter_1_1 || ORIG_REF_NAME==design_4_signal_spliter_1_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlconcat_4_1/design_4_xlconcat_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlconcat_4_1 || ORIG_REF_NAME==design_4_xlconcat_4_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_5_1/design_4_xlslice_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_5_1 || ORIG_REF_NAME==design_4_xlslice_5_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_6_1/design_4_xlslice_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_6_1 || ORIG_REF_NAME==design_4_xlslice_6_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_7_1/design_4_xlslice_7_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_7_1 || ORIG_REF_NAME==design_4_xlslice_7_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_8_1/design_4_xlslice_8_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_8_1 || ORIG_REF_NAME==design_4_xlslice_8_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_9_1/design_4_xlslice_9_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_9_1 || ORIG_REF_NAME==design_4_xlslice_9_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_10_1/design_4_xlslice_10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_10_1 || ORIG_REF_NAME==design_4_xlslice_10_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_processing_system7_0_0/design_4_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_processing_system7_0_0 || ORIG_REF_NAME==design_4_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_rst_ps7_0_125M_0/design_4_rst_ps7_0_125M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_rst_ps7_0_125M_0 || ORIG_REF_NAME==design_4_rst_ps7_0_125M_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xbar_0/design_4_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xbar_0 || ORIG_REF_NAME==design_4_xbar_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_ps7_0_axi_periph_0/design_4_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_4_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_signal_spliter_0_0/design_4_signal_spliter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_signal_spliter_0_0 || ORIG_REF_NAME==design_4_signal_spliter_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_system_ctrl_0_0/design_4_system_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_system_ctrl_0_0 || ORIG_REF_NAME==design_4_system_ctrl_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlconstant_0_2/design_4_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlconstant_0_2 || ORIG_REF_NAME==design_4_xlconstant_0_2} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_0_0/design_4_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_0_0 || ORIG_REF_NAME==design_4_xlslice_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_1_2/design_4_xlslice_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_1_2 || ORIG_REF_NAME==design_4_xlslice_1_2} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlslice_5_2/design_4_xlslice_5_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_xlslice_5_2 || ORIG_REF_NAME==design_4_xlslice_5_2} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axi_gpio_1_2/design_4_axi_gpio_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_axi_gpio_1_2 || ORIG_REF_NAME==design_4_axi_gpio_1_2} -quiet] -quiet

# IP: bd/design_4/ip/design_4_ila_0_0/design_4_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_ila_0_0 || ORIG_REF_NAME==design_4_ila_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_ila_1_0/design_4_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_ila_1_0 || ORIG_REF_NAME==design_4_ila_1_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_ila_2_0/design_4_ila_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_ila_2_0 || ORIG_REF_NAME==design_4_ila_2_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_auto_pc_6/design_4_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_auto_pc_6 || ORIG_REF_NAME==design_4_auto_pc_6} -quiet] -quiet

# IP: bd/design_4/ip/design_4_auto_pc_0/design_4_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_auto_pc_0 || ORIG_REF_NAME==design_4_auto_pc_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_auto_pc_1/design_4_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_auto_pc_1 || ORIG_REF_NAME==design_4_auto_pc_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_auto_pc_2/design_4_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_auto_pc_2 || ORIG_REF_NAME==design_4_auto_pc_2} -quiet] -quiet

# IP: bd/design_4/ip/design_4_auto_pc_3/design_4_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_auto_pc_3 || ORIG_REF_NAME==design_4_auto_pc_3} -quiet] -quiet

# IP: bd/design_4/ip/design_4_auto_pc_4/design_4_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_auto_pc_4 || ORIG_REF_NAME==design_4_auto_pc_4} -quiet] -quiet

# IP: bd/design_4/ip/design_4_auto_pc_5/design_4_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_4_auto_pc_5 || ORIG_REF_NAME==design_4_auto_pc_5} -quiet] -quiet

# XDC: bd/design_4/design_4_ooc.xdc
